# Generated by Django 2.1.2 on 2018-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('rtl', 'Arabian')], max_length=100, unique=True, verbose_name='language')),
                ('main_title', models.CharField(max_length=50)),
                ('main_descrription', models.CharField(max_length=100)),
                ('track_order', models.CharField(max_length=100)),
                ('track_order_description', models.CharField(max_length=100)),
                ('mobile_app', models.CharField(max_length=100)),
                ('mobile_app_description', models.CharField(max_length=100)),
                ('range_title', models.CharField(max_length=100)),
                ('pills', models.CharField(max_length=100)),
                ('pills_description', models.CharField(max_length=100)),
                ('food_delivery', models.CharField(max_length=100)),
                ('clothes', models.CharField(max_length=100)),
                ('clothes_description', models.CharField(max_length=100)),
                ('food_box', models.CharField(max_length=100)),
                ('food_box_description', models.CharField(max_length=100)),
                ('dishes', models.CharField(max_length=100)),
                ('dishes_description', models.CharField(max_length=100)),
                ('taxi', models.CharField(max_length=100)),
                ('taxi_description', models.CharField(max_length=100)),
                ('about_first', models.CharField(max_length=100)),
                ('food_delivery_description', models.CharField(max_length=100)),
                ('about_second', models.CharField(max_length=100)),
                ('about_second_description', models.CharField(max_length=100)),
                ('about_third', models.CharField(max_length=100)),
                ('about_third_description', models.CharField(max_length=100)),
                ('about_four', models.CharField(max_length=100)),
                ('about_four_description', models.CharField(max_length=100)),
                ('about_five', models.CharField(max_length=100)),
                ('about_five_description', models.CharField(max_length=100)),
                ('about_six', models.CharField(max_length=100)),
                ('about_six_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=100, verbose_name='language')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('playMarket', models.CharField(blank=True, default='https://play.google.com/store?hl=ru', max_length=100)),
                ('appStore', models.CharField(blank=True, default='https://www.apple.com/ru/ios/app-store/', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('birth', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('car_manufactore', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('car_year', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('car_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('drive_licence', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('taxi_licence', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('photo_user', models.ImageField(blank=True, default='', upload_to='img/user')),
                ('photo_passport', models.ImageField(blank=True, default='', upload_to='img/user')),
                ('photo_drive_licence', models.ImageField(blank=True, default='', upload_to='img/user')),
                ('photo_insurance', models.ImageField(blank=True, default='', upload_to='img/user')),
                ('exp_drive_licence', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('exp_insurance', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('card_holder', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_moderate', models.BooleanField(default=False)),
                ('user_create_data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
