# Generated by Django 2.1.2 on 2018-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_one_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_one_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_p',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_three_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_three_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_two_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='about_two_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='download_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='download_p',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='download_p_p',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='download_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='register_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='register_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_one_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_one_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_three_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_three_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_two_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='step_two_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='taxi_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='taxi_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='title_descriptiom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='title_p',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='title_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='about_five_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='about_four_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='about_second_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='about_six_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='about_third_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='clothes_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='dishes_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='food_box_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='food_delivery_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='main_descrription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='mobile_app_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='pills_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='taxi_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentclients',
            name='track_order_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contentdrivers',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('rtl', 'Arabian')], max_length=100, unique=True, verbose_name='language'),
        ),
    ]
