# Generated by Django 2.1.2 on 2018-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181119_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentclients',
            name='about_first_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
