# Generated by Django 2.1.2 on 2018-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181120_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='register_description',
            new_name='conditions_descriptiom',
        ),
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='title_descriptiom',
            new_name='conditions_one_description',
        ),
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='download_p_p',
            new_name='conditions_one_title',
        ),
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='register_title',
            new_name='conditions_three_title',
        ),
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='title_p',
            new_name='conditions_title',
        ),
        migrations.RenameField(
            model_name='contentdrivers',
            old_name='title_title',
            new_name='conditions_two_title',
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='conditions_three_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='conditions_two_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='taxi_app_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentdrivers',
            name='taxi_app_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
