# Generated by Django 2.1.2 on 2018-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181123_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdrivers',
            name='button_one',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contentdrivers',
            name='button_two',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contentdrivers',
            name='header',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
